name: Checkstyle

on: [pull_request, workflow_dispatch]

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dbelyaev/action-checkstyle@test-run-as-non-root-user
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
